VSIXDoxygenPreviewExtension: DoxPreviewExt.DoxUtil.DoxTokenTaggerHelper Class Reference
DoxPreviewExt.DoxUtil.DoxTokenTaggerHelper Class Reference
simple doxygen special command parser
Static Public Member Functions
static DoxTokenTag TagHitTest (ITagAggregator< DoxTokenTag > aggregator, ITextSnapshot snapshot, int pos)
find tag at position
static List< DoxTokenTag > GenerateTags (IEnumerable< SnapshotSpan > spans)
static bool FindCmdFileRef (List< SnapshotSpan > identList, string startCmd, SortedSet< string > kinds, int start_inx, out bool valid, out int file_name_inx, out int sequnce_end_inx)
static bool FindCmdBlock (List< SnapshotSpan > identList, string startCmd, string endCmd, int start_inx, out int sequnce_end_inx)
static bool FindCmdToken (List< SnapshotSpan > identList, string endCmd, int strat_inx, out int token_inx)
static bool IsDoxBlockCommentStart (string buffer, int pos)
static bool IsBlockCommentStart (string buffer, int pos)
static bool IsBlockCommentEnd (string buffer, int pos)
static bool IsDoxLineCommentStart (string buffer, int pos)
static bool IsLineCommentStart (string buffer, int pos)
static bool IsLineCommentEnd (string buffer, int pos)
static IEnumerable< SnapshotSpan > CommentSpans (SnapshotSpan span)
static List< SnapshotSpan > LexIdentifiers (SnapshotSpan span)
static bool IsStartOfIdent (char c)
static bool IsStartOfCommand (char c)
static bool IsTokenChar (char c)
Detailed Description
simple doxygen special command parser
Member Function Documentation
CommentSpans()
static IEnumerable<SnapshotSpan> DoxPreviewExt.DoxUtil.DoxTokenTaggerHelper.CommentSpans (SnapshotSpan span) inline static
FindCmdBlock()
static bool DoxPreviewExt.DoxUtil.DoxTokenTaggerHelper.FindCmdBlock (List< SnapshotSpan > identList, string startCmd, string endCmd, int start_inx, out int sequnce_end_inx) inline static
FindCmdFileRef()
static bool DoxPreviewExt.DoxUtil.DoxTokenTaggerHelper.FindCmdFileRef (List< SnapshotSpan > identList, string startCmd, SortedSet< string > kinds, int start_inx, out bool valid, out int file_name_inx, out int sequnce_end_inx) inline static
FindCmdToken()
static bool DoxPreviewExt.DoxUtil.DoxTokenTaggerHelper.FindCmdToken (List< SnapshotSpan > identList, string endCmd, int strat_inx, out int token_inx) inline static
GenerateTags()
static List<DoxTokenTag> DoxPreviewExt.DoxUtil.DoxTokenTaggerHelper.GenerateTags (IEnumerable< SnapshotSpan > spans) inline static
References DoxPreviewExt.DoxUtil.CManager.Manager.
Referenced by DoxPreviewExt.DoxUtil.DoxTokenTagger.ReParse().
IsBlockCommentEnd()
static bool DoxPreviewExt.DoxUtil.DoxTokenTaggerHelper.IsBlockCommentEnd (string buffer, int pos) inline static
IsBlockCommentStart()
static bool DoxPreviewExt.DoxUtil.DoxTokenTaggerHelper.IsBlockCommentStart (string buffer, int pos) inline static
IsDoxBlockCommentStart()
static bool DoxPreviewExt.DoxUtil.DoxTokenTaggerHelper.IsDoxBlockCommentStart (string buffer, int pos) inline static
IsDoxLineCommentStart()
static bool DoxPreviewExt.DoxUtil.DoxTokenTaggerHelper.IsDoxLineCommentStart (string buffer, int pos) inline static
IsLineCommentEnd()
static bool DoxPreviewExt.DoxUtil.DoxTokenTaggerHelper.IsLineCommentEnd (string buffer, int pos) inline static
IsLineCommentStart()
static bool DoxPreviewExt.DoxUtil.DoxTokenTaggerHelper.IsLineCommentStart (string buffer, int pos) inline static
IsStartOfCommand()
static bool DoxPreviewExt.DoxUtil.DoxTokenTaggerHelper.IsStartOfCommand (char c) inline static
IsStartOfIdent()
static bool DoxPreviewExt.DoxUtil.DoxTokenTaggerHelper.IsStartOfIdent (char c) inline static
IsTokenChar()
static bool DoxPreviewExt.DoxUtil.DoxTokenTaggerHelper.IsTokenChar (char c) inline static
LexIdentifiers()
static List<SnapshotSpan> DoxPreviewExt.DoxUtil.DoxTokenTaggerHelper.LexIdentifiers (SnapshotSpan span) inline static
TagHitTest()
static DoxTokenTag DoxPreviewExt.DoxUtil.DoxTokenTaggerHelper.TagHitTest (ITagAggregator< DoxTokenTag > aggregator, ITextSnapshot snapshot, int pos) inline static
find tag at position
Referenced by DoxPreviewExt.DoxUtil.CmdQuickInfoSource.AugmentQuickInfoSession(), and DoxPreviewExt.DoxUtil.CMouseProcessorProvider.CMouseProcessor.FindSpanTag().
The documentation for this class was generated from the following file:
C:/source/C#/VSIX-Doxygen-Extension/DoxPreviewExt/DoxUtil/DoxUtilTagger.cs