VSIX Doxygen Preview Extension: DoxPreviewExt.DoxUtil.COptions Class Reference
DoxPreviewExt.DoxUtil.COptions Class Reference
Public Member Functions
COptions (Microsoft.VisualStudio.Shell.Package package)
void ClearPaths ()
Clear path cache.
void UpdateConfiguration ()
read doxygen configuration from file
Properties
Microsoft.VisualStudio.Shell.Package Package [get]
static string DefaultSourceBrowser [get, set]
static string DefaultConfigFile = ExtensionCommon.ExtensionContext.constDoxygenSourceBrowserURL [get, set]
string CurrentSourceBrowser [get]
string CurrentDoxygenConfigFile [get]
string CurrentDotTool [get]
string CurrentMscGenTool [get]
string CurrentPlantUmlTool [get]
string CurrentMimeTeXTool [get]
bool UseSourceBrowser [get]
Reference doxygen documentation on server.
bool UseConfigFile [get]
Interpret doxygen configuration file.
string DotExe [get]
Get Executable path and file of Dot Graph to bitmap converter.
string MscGenExe [get]
Get Executable path and file of Message Sequence Chart Graph to bitmap converter.
string PlantUmlJar [get]
Get Path of PlantUML to bitmap converter.
string MimeTeXExe [get]
Get Executable path and file of mimeTeX Latex Formula to bitmap converter.
bool ClickOnRef [get]
Browse Reference, if clicked on.
bool GeneralQT [get]
Show general Quicktips.
bool RefQT [get]
Show reference URL in Quicktip.
bool ImageQT [get]
Show bitmap preview in Quicktip.
bool DotQT [get]
Show Dot Graph preview in Quicktip.
bool MscQT [get]
Show Message Sequence Chart preview in Quicktip.
bool PlantUmlQT [get]
Show Plant UML preview in Quicktip.
bool LatexFormulaQT [get]
Show Latex Formula preview in Quicktip.
List< string > ImagePaths [get]
List< string > DotPaths [get]
List< string > MscPaths [get]
List< string > DiaPaths [get]
List< string > UmlPaths [get]
string DoxRootPath [get]
get root path of doxygen project
bool DoxHtmlOutput [get]
test if html output is enabled
string LocalHTMLPath [get]
get local HTML diectory
bool DoxFileMathJaxSuport [get]
test if mathjax is enabled (Latex formula)
bool DoxFileDotGraphSuport [get]
test if dot graph is enabled
string DoxFileMathJaxPath [get]
get mathjax URL
string DoxFileDotGraphBinPath [get]
get dot graph binaries path (graphviz)
string DoxFileMscgenBinPath [get]
get message sequence chart binaries path (mscgen)
string DoxFileDiaBinPath [get]
get dia binaries path
string DoxFilePlantUmlJarPath [get]
get path of plantuml.jar (Plant UML)
Private Member Functions
T_PAGE Page< T_PAGE > ()
bool SourceBrowserValid ()
Tests if source browser is valid.
bool LocalDocumentationValid ()
Tests if local doxgen documantation is valid.
bool AnyDocumentationValid ()
Test if any documentation valid.
bool ConfigFileValid ()
Tests if configuration file is valid.
void FindDotExe ()
finds dot.exe
void FindMscGenExe ()
finds mscgen.exe
void FindPlantUmlJar ()
finds plantuml.jar
void FindMimeTeXExe ()
finds mimetex.exe
bool DotValid ()
Tests if Dot Graph convert tool is valid.
bool MscGenValid ()
Tests if Message Sequence Chart Graph convert tool is valid.
bool PlantUmlValide ()
Tests if Message Sequence Chart Graph convert tool is valid.
bool MimeTeXValid ()
Tests if mimeTeX convert tool is valid.
void ReadConfiguration ()
read doxygen configuration from file
List< string > ConvertPaths (string key, string rootPath)
conver local paths to avsolute paths
string ConfigValue (string key)
test if html output is enabled
Private Attributes
string _currentSourceBrowser = ""
string _currentDoxygenConfigFile = ""
string _currentDotExe = null
string _currentMscGenExe = null
string _currentPlantUmlJar = null
string _currentMimeTeXExe = null
SortedDictionary< string, List< string > > config_ = new SortedDictionary<string, List<string>>()
List< string > imagePaths_ = new List<string>()
List< string > dotPaths_ = new List<string>()
List< string > mscPaths_ = new List<string>()
List< string > diaPaths_ = new List<string>()
List< string > umlPaths_ = new List<string>()
Constructor & Destructor Documentation
COptions()
DoxPreviewExt.DoxUtil.COptions.COptions (Microsoft.VisualStudio.Shell.Package package) inline
Member Function Documentation
AnyDocumentationValid()
bool DoxPreviewExt.DoxUtil.COptions.AnyDocumentationValid () inline private
Test if any documentation valid.
ClearPaths()
void DoxPreviewExt.DoxUtil.COptions.ClearPaths () inline
Clear path cache.
ConfigFileValid()
bool DoxPreviewExt.DoxUtil.COptions.ConfigFileValid () inline private
Tests if configuration file is valid.
ConfigValue()
string DoxPreviewExt.DoxUtil.COptions.ConfigValue (string key) inline private
test if html output is enabled
ConvertPaths()
List<string> DoxPreviewExt.DoxUtil.COptions.ConvertPaths (string key, string rootPath) inline private
conver local paths to avsolute paths
DotValid()
bool DoxPreviewExt.DoxUtil.COptions.DotValid () inline private
Tests if Dot Graph convert tool is valid.
FindDotExe()
void DoxPreviewExt.DoxUtil.COptions.FindDotExe () inline private
finds dot.exe
References ExtensionCommon.ExtensionContext.GetDotExe().
FindMimeTeXExe()
void DoxPreviewExt.DoxUtil.COptions.FindMimeTeXExe () inline private
finds mimetex.exe
References ExtensionCommon.ExtensionContext.GetMimeTeXExe().
FindMscGenExe()
void DoxPreviewExt.DoxUtil.COptions.FindMscGenExe () inline private
finds mscgen.exe
References ExtensionCommon.ExtensionContext.GetMscGenExe().
FindPlantUmlJar()
void DoxPreviewExt.DoxUtil.COptions.FindPlantUmlJar () inline private
finds plantuml.jar
References ExtensionCommon.ExtensionContext.GetPlantUmlJar().
LocalDocumentationValid()
bool DoxPreviewExt.DoxUtil.COptions.LocalDocumentationValid () inline private
Tests if local doxgen documantation is valid.
MimeTeXValid()
bool DoxPreviewExt.DoxUtil.COptions.MimeTeXValid () inline private
Tests if mimeTeX convert tool is valid.
MscGenValid()
bool DoxPreviewExt.DoxUtil.COptions.MscGenValid () inline private
Tests if Message Sequence Chart Graph convert tool is valid.
Page< T_PAGE >()
T_PAGE DoxPreviewExt.DoxUtil.COptions.Page< T_PAGE > () inline private
Type Constraints
T_PAGE : class
PlantUmlValide()
bool DoxPreviewExt.DoxUtil.COptions.PlantUmlValide () inline private
Tests if Message Sequence Chart Graph convert tool is valid.
ReadConfiguration()
void DoxPreviewExt.DoxUtil.COptions.ReadConfiguration () inline private
read doxygen configuration from file
SourceBrowserValid()
bool DoxPreviewExt.DoxUtil.COptions.SourceBrowserValid () inline private
Tests if source browser is valid.
UpdateConfiguration()
void DoxPreviewExt.DoxUtil.COptions.UpdateConfiguration () inline
read doxygen configuration from file
Referenced by DoxPreviewExt.DoxUtil.CManager.Update().
Member Data Documentation
_currentDotExe
string DoxPreviewExt.DoxUtil.COptions._currentDotExe = null private
_currentDoxygenConfigFile
string DoxPreviewExt.DoxUtil.COptions._currentDoxygenConfigFile = "" private
_currentMimeTeXExe
string DoxPreviewExt.DoxUtil.COptions._currentMimeTeXExe = null private
_currentMscGenExe
string DoxPreviewExt.DoxUtil.COptions._currentMscGenExe = null private
_currentPlantUmlJar
string DoxPreviewExt.DoxUtil.COptions._currentPlantUmlJar = null private
_currentSourceBrowser
string DoxPreviewExt.DoxUtil.COptions._currentSourceBrowser = "" private
config_
SortedDictionary<string, List<string> > DoxPreviewExt.DoxUtil.COptions.config_ = new SortedDictionary<string, List<string>>() private
diaPaths_
List<string> DoxPreviewExt.DoxUtil.COptions.diaPaths_ = new List<string>() private
dotPaths_
List<string> DoxPreviewExt.DoxUtil.COptions.dotPaths_ = new List<string>() private
imagePaths_
List<string> DoxPreviewExt.DoxUtil.COptions.imagePaths_ = new List<string>() private
mscPaths_
List<string> DoxPreviewExt.DoxUtil.COptions.mscPaths_ = new List<string>() private
umlPaths_
List<string> DoxPreviewExt.DoxUtil.COptions.umlPaths_ = new List<string>() private
Property Documentation
ClickOnRef
bool DoxPreviewExt.DoxUtil.COptions.ClickOnRef get
Browse Reference, if clicked on.
CurrentDotTool
string DoxPreviewExt.DoxUtil.COptions.CurrentDotTool get
CurrentDoxygenConfigFile
string DoxPreviewExt.DoxUtil.COptions.CurrentDoxygenConfigFile get
CurrentMimeTeXTool
string DoxPreviewExt.DoxUtil.COptions.CurrentMimeTeXTool get
CurrentMscGenTool
string DoxPreviewExt.DoxUtil.COptions.CurrentMscGenTool get
CurrentPlantUmlTool
string DoxPreviewExt.DoxUtil.COptions.CurrentPlantUmlTool get
CurrentSourceBrowser
string DoxPreviewExt.DoxUtil.COptions.CurrentSourceBrowser get
Referenced by DoxPreviewExt.DoxUtil.CManager.Update().
DefaultConfigFile
string DoxPreviewExt.DoxUtil.COptions.DefaultConfigFile = ExtensionCommon.ExtensionContext.constDoxygenSourceBrowserURL static get set
Referenced by DoxPreviewExt.DoxUtil.CManager.UpdateConfigFile().
DefaultSourceBrowser
string DoxPreviewExt.DoxUtil.COptions.DefaultSourceBrowser static get set
Referenced by DoxPreviewExt.DoxUtil.CManager.UpdateConfigFile().
DiaPaths
List<string> DoxPreviewExt.DoxUtil.COptions.DiaPaths get
DotExe
string DoxPreviewExt.DoxUtil.COptions.DotExe get
Get Executable path and file of Dot Graph to bitmap converter.
DotPaths
List<string> DoxPreviewExt.DoxUtil.COptions.DotPaths get
DotQT
bool DoxPreviewExt.DoxUtil.COptions.DotQT get
Show Dot Graph preview in Quicktip.
DoxFileDiaBinPath
string DoxPreviewExt.DoxUtil.COptions.DoxFileDiaBinPath get
get dia binaries path
DoxFileDotGraphBinPath
string DoxPreviewExt.DoxUtil.COptions.DoxFileDotGraphBinPath get
get dot graph binaries path (graphviz)
DoxFileDotGraphSuport
bool DoxPreviewExt.DoxUtil.COptions.DoxFileDotGraphSuport get
test if dot graph is enabled
DoxFileMathJaxPath
string DoxPreviewExt.DoxUtil.COptions.DoxFileMathJaxPath get
get mathjax URL
DoxFileMathJaxSuport
bool DoxPreviewExt.DoxUtil.COptions.DoxFileMathJaxSuport get
test if mathjax is enabled (Latex formula)
DoxFileMscgenBinPath
string DoxPreviewExt.DoxUtil.COptions.DoxFileMscgenBinPath get
get message sequence chart binaries path (mscgen)
DoxFilePlantUmlJarPath
string DoxPreviewExt.DoxUtil.COptions.DoxFilePlantUmlJarPath get
get path of plantuml.jar (Plant UML)
DoxHtmlOutput
bool DoxPreviewExt.DoxUtil.COptions.DoxHtmlOutput get
test if html output is enabled
DoxRootPath
string DoxPreviewExt.DoxUtil.COptions.DoxRootPath get
get root path of doxygen project
GeneralQT
bool DoxPreviewExt.DoxUtil.COptions.GeneralQT get
Show general Quicktips.
ImagePaths
List<string> DoxPreviewExt.DoxUtil.COptions.ImagePaths get
ImageQT
bool DoxPreviewExt.DoxUtil.COptions.ImageQT get
Show bitmap preview in Quicktip.
LatexFormulaQT
bool DoxPreviewExt.DoxUtil.COptions.LatexFormulaQT get
Show Latex Formula preview in Quicktip.
LocalHTMLPath
string DoxPreviewExt.DoxUtil.COptions.LocalHTMLPath get
get local HTML diectory
MimeTeXExe
string DoxPreviewExt.DoxUtil.COptions.MimeTeXExe get
Get Executable path and file of mimeTeX Latex Formula to bitmap converter.
MscGenExe
string DoxPreviewExt.DoxUtil.COptions.MscGenExe get
Get Executable path and file of Message Sequence Chart Graph to bitmap converter.
MscPaths
List<string> DoxPreviewExt.DoxUtil.COptions.MscPaths get
MscQT
bool DoxPreviewExt.DoxUtil.COptions.MscQT get
Show Message Sequence Chart preview in Quicktip.
Package
Microsoft.VisualStudio.Shell.Package DoxPreviewExt.DoxUtil.COptions.Package get
PlantUmlJar
string DoxPreviewExt.DoxUtil.COptions.PlantUmlJar get
Get Path of PlantUML to bitmap converter.
PlantUmlQT
bool DoxPreviewExt.DoxUtil.COptions.PlantUmlQT get
Show Plant UML preview in Quicktip.
RefQT
bool DoxPreviewExt.DoxUtil.COptions.RefQT get
Show reference URL in Quicktip.
UmlPaths
List<string> DoxPreviewExt.DoxUtil.COptions.UmlPaths get
UseConfigFile
bool DoxPreviewExt.DoxUtil.COptions.UseConfigFile get
Interpret doxygen configuration file.
UseSourceBrowser
bool DoxPreviewExt.DoxUtil.COptions.UseSourceBrowser get
Reference doxygen documentation on server.
The documentation for this class was generated from the following file:
C:/source/C#/VSIX-Doxygen-Extension/DoxPreviewExt/DoxUtil/DoxUtilOptions.cs