VSIXDoxygenPreviewExtension: DoxPreviewExt.DoxUtil.CPreviewImageCollection Class Reference
DoxPreviewExt.DoxUtil.CPreviewImageCollection Class Reference
Public Member Functions
CPreviewImageCollection ()
IPreviewImage Find (string key)
void Remove (string key)
void RemoveImageFile (string filePath)
void Add (string key, IPreviewImage image)
string NewTempPreviewFileName ()
Get new name of temporary preview file name.
Private Attributes
SortedDictionary< string, IPreviewImage > tempPreviewFiles_ = null
int nextTempPreviewFileNumber_ = 0
Constructor & Destructor Documentation
CPreviewImageCollection()
DoxPreviewExt.DoxUtil.CPreviewImageCollection.CPreviewImageCollection () inline
Member Function Documentation
Add()
void DoxPreviewExt.DoxUtil.CPreviewImageCollection.Add (string key, IPreviewImage image) inline
References DoxPreviewExt.DoxUtil.IPreviewImage.GetImageFile().
Referenced by DoxPreviewExt.DoxUtil.CManager.GenerateDotFileGraphPreview(), DoxPreviewExt.DoxUtil.CManager.GenerateDotGraphPreview(), DoxPreviewExt.DoxUtil.CManager.GenerateLatexFormulaPreview(), DoxPreviewExt.DoxUtil.CManager.GenerateMscFileGraphPreview(), DoxPreviewExt.DoxUtil.CManager.GenerateMscGraphPreview(), and DoxPreviewExt.DoxUtil.CManager.GeneratePlatUMLPreview().
Find()
IPreviewImage DoxPreviewExt.DoxUtil.CPreviewImageCollection.Find (string key) inline
Referenced by DoxPreviewExt.DoxUtil.CManager.GenerateDotFileGraphPreview(), DoxPreviewExt.DoxUtil.CManager.GenerateDotGraphPreview(), DoxPreviewExt.DoxUtil.CManager.GenerateLatexFormulaPreview(), DoxPreviewExt.DoxUtil.CManager.GenerateMscFileGraphPreview(), DoxPreviewExt.DoxUtil.CManager.GenerateMscGraphPreview(), and DoxPreviewExt.DoxUtil.CManager.GeneratePlatUMLPreview().
NewTempPreviewFileName()
string DoxPreviewExt.DoxUtil.CPreviewImageCollection.NewTempPreviewFileName () inline
Get new name of temporary preview file name.
Referenced by DoxPreviewExt.DoxUtil.CPreviewImageBase.CPreviewImageBase().
Remove()
void DoxPreviewExt.DoxUtil.CPreviewImageCollection.Remove (string key) inline
RemoveImageFile()
void DoxPreviewExt.DoxUtil.CPreviewImageCollection.RemoveImageFile (string filePath) inline
Member Data Documentation
nextTempPreviewFileNumber_
int DoxPreviewExt.DoxUtil.CPreviewImageCollection.nextTempPreviewFileNumber_ = 0 private
tempPreviewFiles_
SortedDictionary<string, IPreviewImage> DoxPreviewExt.DoxUtil.CPreviewImageCollection.tempPreviewFiles_ = null private
The documentation for this class was generated from the following file:
C:/source/C#/VSIX-Doxygen-Extension/DoxPreviewExt/DoxUtil/DoxUtilManager.cs