VSIX Doxygen Preview Extension: DoxPreviewExt.DoxUtil.CManager Class Reference
DoxPreviewExt.DoxUtil.CManager Class Reference
Public Member Functions
CManager (Microsoft.VisualStudio.Shell.Package package, DTE2 applicationObject)
ctor
void Update ()
bool IsKnownCommand (string cmdStr)
void UpdateURL (string mainUrl)
update main URL and regenerate reference association map
void UpdateLocalHtml (string localPath)
update local path and regenerate reference association map
void ClearDoxygenCache ()
clear doxygen cache
string FindDoxygenLink (string doxRef, bool recreateIfEmpty)
find HTML link from reference name
string FindFirstDoxygenReference (string text)
parse text and find the first doxgen reference
string FindFirstDoxygenLink (string text, bool recreateIfEmpty)
find the first doxygen reference and find the associated HTML link
string FindImageFilePath (string filename)
find a file path by a image file name
string FindDotFilePath (string filename)
find a file path by a dot graph file name
string FindMscFilePath (string filename)
find a file path by a message sequence chart file name
string FindDiaFilePath (string filename)
find a file path by a dia file name
System.Windows.Controls.Image GenerateDotGraphPreview (string sourceCode)
generate temporary image file from dot graph source code
System.Windows.Controls.Image GenerateDotFileGraphPreview (string filename)
generate temporary image file from dot graph file
System.Windows.Controls.Image GenerateMscGraphPreview (string sourceCode)
generate temporary image file from message sequence chart source code
System.Windows.Controls.Image GenerateMscFileGraphPreview (string filename)
generate temporary image file from message sequence chart file
System.Windows.Controls.Image GeneratePlatUMLPreview (string sourceCode)
generate temporary image file from PlatUML source code
System.Windows.Controls.Image GenerateLatexFormulaPreview (string formula)
generate temporary image file from PlatUML source code
Static Public Member Functions
static void OpenHTML (string path)
open content in standard browser
static System.Windows.Controls.Image LoadOrCreateBitmapImage (string imagePath)
laod image form file
static string GenerateMD5Key (string sourceCode)
generates MD5 key from source code
Package Functions
string GetShellDefaultBrowser ()
get the standard browser path [http://stackoverflow.com/questions/13621467/how-to-find-default-web-browser-using-c]
Properties
static string DoxCommadsHelpURL [get]
static string GraphvizHelpURL [get]
static string MscgenHelpURL [get]
static string PlanUMLHelpURL [get]
static string LatexHelpURL [get]
static string DoxExtTempPath [get]
Microsoft.VisualStudio.Shell.Package Package [get]
DTE2 ApplicationObject [get]
COptions Options [get]
string SolutionFile [get]
CCache Cache [get]
static CManager Manager [get]
Private Member Functions
void UpdateConfigFile ()
reads and interprets current solution form application obejct
void UpdateFilePaths (ref CFileMap filemap, List< string > imagePaths)
update image path and regenerate image location map
string FileKeyFromName (string fileName)
make file key from file name
Static Private Member Functions
static void UpdateURL (ref CLinkMap linkMap, string mainUrl)
update URL and regenerate reference association map
static string GetMd5Hash (MD5 md5Hash, string input)
Generate MD5 hash from UTF8 string.
Private Attributes
Microsoft.VisualStudio.Shell.Package _package = null
shell package
DTE2 _applicationObject = null
application object
COptions _options = null
doxygen options
string _solutionFile = null
current solution
CCache _cache = null
cache data
CPreviewImageCollection tempPreviewFiles_ = new CPreviewImageCollection()
Static Private Attributes
static HashSet< string > commandIDs_
static CManager _doxManger = null
doxgen utility manager singleton
static string defaultBrowser = null
Constructor & Destructor Documentation
CManager()
DoxPreviewExt.DoxUtil.CManager.CManager (Microsoft.VisualStudio.Shell.Package package, DTE2 applicationObject) inline
ctor
Member Function Documentation
ClearDoxygenCache()
void DoxPreviewExt.DoxUtil.CManager.ClearDoxygenCache () inline
clear doxygen cache
FileKeyFromName()
string DoxPreviewExt.DoxUtil.CManager.FileKeyFromName (string fileName) inline private
make file key from file name
FindDiaFilePath()
string DoxPreviewExt.DoxUtil.CManager.FindDiaFilePath (string filename) inline
find a file path by a dia file name
FindDotFilePath()
string DoxPreviewExt.DoxUtil.CManager.FindDotFilePath (string filename) inline
find a file path by a dot graph file name
FindDoxygenLink()
string DoxPreviewExt.DoxUtil.CManager.FindDoxygenLink (string doxRef, bool recreateIfEmpty) inline
find HTML link from reference name
FindFirstDoxygenLink()
string DoxPreviewExt.DoxUtil.CManager.FindFirstDoxygenLink (string text, bool recreateIfEmpty) inline
find the first doxygen reference and find the associated HTML link
FindFirstDoxygenReference()
string DoxPreviewExt.DoxUtil.CManager.FindFirstDoxygenReference (string text) inline
parse text and find the first doxgen reference
FindImageFilePath()
string DoxPreviewExt.DoxUtil.CManager.FindImageFilePath (string filename) inline
find a file path by a image file name
FindMscFilePath()
string DoxPreviewExt.DoxUtil.CManager.FindMscFilePath (string filename) inline
find a file path by a message sequence chart file name
GenerateDotFileGraphPreview()
System.Windows.Controls.Image DoxPreviewExt.DoxUtil.CManager.GenerateDotFileGraphPreview (string filename) inline
generate temporary image file from dot graph file
References DoxPreviewExt.DoxUtil.CPreviewImageCollection.Add(), and DoxPreviewExt.DoxUtil.CPreviewImageCollection.Find().
GenerateDotGraphPreview()
System.Windows.Controls.Image DoxPreviewExt.DoxUtil.CManager.GenerateDotGraphPreview (string sourceCode) inline
generate temporary image file from dot graph source code
References DoxPreviewExt.DoxUtil.CPreviewImageCollection.Add(), and DoxPreviewExt.DoxUtil.CPreviewImageCollection.Find().
GenerateLatexFormulaPreview()
System.Windows.Controls.Image DoxPreviewExt.DoxUtil.CManager.GenerateLatexFormulaPreview (string formula) inline
generate temporary image file from PlatUML source code
References DoxPreviewExt.DoxUtil.CPreviewImageCollection.Add(), and DoxPreviewExt.DoxUtil.CPreviewImageCollection.Find().
GenerateMD5Key()
static string DoxPreviewExt.DoxUtil.CManager.GenerateMD5Key (string sourceCode) inline static
generates MD5 key from source code
GenerateMscFileGraphPreview()
System.Windows.Controls.Image DoxPreviewExt.DoxUtil.CManager.GenerateMscFileGraphPreview (string filename) inline
generate temporary image file from message sequence chart file
References DoxPreviewExt.DoxUtil.CPreviewImageCollection.Add(), and DoxPreviewExt.DoxUtil.CPreviewImageCollection.Find().
GenerateMscGraphPreview()
System.Windows.Controls.Image DoxPreviewExt.DoxUtil.CManager.GenerateMscGraphPreview (string sourceCode) inline
generate temporary image file from message sequence chart source code
References DoxPreviewExt.DoxUtil.CPreviewImageCollection.Add(), and DoxPreviewExt.DoxUtil.CPreviewImageCollection.Find().
GeneratePlatUMLPreview()
System.Windows.Controls.Image DoxPreviewExt.DoxUtil.CManager.GeneratePlatUMLPreview (string sourceCode) inline
generate temporary image file from PlatUML source code
References DoxPreviewExt.DoxUtil.CPreviewImageCollection.Add(), and DoxPreviewExt.DoxUtil.CPreviewImageCollection.Find().
GetMd5Hash()
static string DoxPreviewExt.DoxUtil.CManager.GetMd5Hash (MD5 md5Hash, string input) inline static private
Generate MD5 hash from UTF8 string.
GetShellDefaultBrowser()
string DoxPreviewExt.DoxUtil.CManager.GetShellDefaultBrowser () inline package
get the standard browser path [http://stackoverflow.com/questions/13621467/how-to-find-default-web-browser-using-c]
IsKnownCommand()
bool DoxPreviewExt.DoxUtil.CManager.IsKnownCommand (string cmdStr) inline
Tests if the command is a well known doxygen special command cf [https://www.stack.nl/~dimitri/doxygen/manual/commands.html]
LoadOrCreateBitmapImage()
static System.Windows.Controls.Image DoxPreviewExt.DoxUtil.CManager.LoadOrCreateBitmapImage (string imagePath) inline static
laod image form file
Referenced by DoxPreviewExt.DoxUtil.CmdQuickInfoSource.AddImage(), DoxPreviewExt.DoxUtil.CPlantUMLImage.GetValidImage(), DoxPreviewExt.DoxUtil.CMscGraphImage.GetValidImage(), DoxPreviewExt.DoxUtil.CLatexFormulaImage.GetValidImage(), and DoxPreviewExt.DoxUtil.CDotGraphImage.GetValidImage().
OpenHTML()
static void DoxPreviewExt.DoxUtil.CManager.OpenHTML (string path) inline static
open content in standard browser
Update()
void DoxPreviewExt.DoxUtil.CManager.Update () inline
References DoxPreviewExt.DoxUtil.COptions.CurrentSourceBrowser, and DoxPreviewExt.DoxUtil.COptions.UpdateConfiguration().
UpdateConfigFile()
void DoxPreviewExt.DoxUtil.CManager.UpdateConfigFile () inline private
reads and interprets current solution form application obejct
References ExtensionCommon.ExtensionContext.constDoxygenSourceBrowserURL, DoxPreviewExt.DoxUtil.COptions.DefaultConfigFile, DoxPreviewExt.DoxUtil.COptions.DefaultSourceBrowser, ExtensionCommon.ExtensionContext.DoxygenPreviewTemplatePath, DoxPreviewExt.DoxUtil.CDoxSrcConfigXML.GetConfigFile(), DoxPreviewExt.DoxUtil.CDoxSrcConfigXML.GetSource(), and DoxPreviewExt.DoxUtil.CDoxSrcConfigXML.Read().
UpdateFilePaths()
void DoxPreviewExt.DoxUtil.CManager.UpdateFilePaths (ref CFileMap filemap, List< string > imagePaths) inline private
update image path and regenerate image location map
UpdateLocalHtml()
void DoxPreviewExt.DoxUtil.CManager.UpdateLocalHtml (string localPath) inline
update local path and regenerate reference association map
UpdateURL() [1/2]
static void DoxPreviewExt.DoxUtil.CManager.UpdateURL (ref CLinkMap linkMap, string mainUrl) inline static private
update URL and regenerate reference association map
UpdateURL() [2/2]
void DoxPreviewExt.DoxUtil.CManager.UpdateURL (string mainUrl) inline
update main URL and regenerate reference association map
Member Data Documentation
_applicationObject
DTE2 DoxPreviewExt.DoxUtil.CManager._applicationObject = null private
application object
_cache
CCache DoxPreviewExt.DoxUtil.CManager._cache = null private
cache data
_doxManger
CManager DoxPreviewExt.DoxUtil.CManager._doxManger = null static private
doxgen utility manager singleton
_options
COptions DoxPreviewExt.DoxUtil.CManager._options = null private
doxygen options
_package
Microsoft.VisualStudio.Shell.Package DoxPreviewExt.DoxUtil.CManager._package = null private
shell package
_solutionFile
string DoxPreviewExt.DoxUtil.CManager._solutionFile = null private
current solution
commandIDs_
HashSet<string> DoxPreviewExt.DoxUtil.CManager.commandIDs_ static private
List of a well known doxygen special command cf [https://www.stack.nl/~dimitri/doxygen/manual/commands.html]
defaultBrowser
string DoxPreviewExt.DoxUtil.CManager.defaultBrowser = null static private
tempPreviewFiles_
CPreviewImageCollection DoxPreviewExt.DoxUtil.CManager.tempPreviewFiles_ = new CPreviewImageCollection() private
Property Documentation
ApplicationObject
DTE2 DoxPreviewExt.DoxUtil.CManager.ApplicationObject get
Cache
CCache DoxPreviewExt.DoxUtil.CManager.Cache get private
DoxCommadsHelpURL
string DoxPreviewExt.DoxUtil.CManager.DoxCommadsHelpURL static get
DoxExtTempPath
string DoxPreviewExt.DoxUtil.CManager.DoxExtTempPath static get
Referenced by DoxPreviewExt.DoxUtil.CDotGraphImage.CDotGraphImage(), DoxPreviewExt.DoxUtil.CLatexFormulaImage.CLatexFormulaImage(), DoxPreviewExt.DoxUtil.CMscGraphImage.CMscGraphImage(), and DoxPreviewExt.DoxUtil.CPlantUMLImage.CPlantUMLImage().
GraphvizHelpURL
string DoxPreviewExt.DoxUtil.CManager.GraphvizHelpURL static get
LatexHelpURL
string DoxPreviewExt.DoxUtil.CManager.LatexHelpURL static get
Manager
CManager DoxPreviewExt.DoxUtil.CManager.Manager static get
Referenced by DoxPreviewExt.DoxUtil.DoxTokenTaggerHelper.GenerateTags().
MscgenHelpURL
string DoxPreviewExt.DoxUtil.CManager.MscgenHelpURL static get
Options
COptions DoxPreviewExt.DoxUtil.CManager.Options get
Package
Microsoft.VisualStudio.Shell.Package DoxPreviewExt.DoxUtil.CManager.Package get
PlanUMLHelpURL
string DoxPreviewExt.DoxUtil.CManager.PlanUMLHelpURL static get
SolutionFile
string DoxPreviewExt.DoxUtil.CManager.SolutionFile get
The documentation for this class was generated from the following file:
C:/source/C#/VSIX-Doxygen-Extension/DoxPreviewExt/DoxUtil/DoxUtilManager.cs