VSIXDoxygenPreviewExtension: DoxPreviewExt.DoxUtil.CDoxSrcConfigXML Class Reference
DoxPreviewExt.DoxUtil.CDoxSrcConfigXML Class Reference
Public Member Functions
string GetSource ()
string GetConfigFile ()
CDoxSrcConfigXML (string file)
ctor
bool Read ()
read doxygen configuration
Private Attributes
string _file = ""
xml doxygen source specification file
SortedDictionary< string, string > _elemDictionary = null
Constructor & Destructor Documentation
CDoxSrcConfigXML()
DoxPreviewExt.DoxUtil.CDoxSrcConfigXML.CDoxSrcConfigXML (string file) inline
ctor
Member Function Documentation
GetConfigFile()
string DoxPreviewExt.DoxUtil.CDoxSrcConfigXML.GetConfigFile () inline
Referenced by DoxPreviewExt.DoxUtil.CManager.UpdateConfigFile().
GetSource()
string DoxPreviewExt.DoxUtil.CDoxSrcConfigXML.GetSource () inline
Referenced by DoxPreviewExt.DoxUtil.CManager.UpdateConfigFile().
Read()
bool DoxPreviewExt.DoxUtil.CDoxSrcConfigXML.Read () inline
read doxygen configuration
Referenced by DoxPreviewExt.DoxUtil.CManager.UpdateConfigFile().
Member Data Documentation
_elemDictionary
SortedDictionary<string, string> DoxPreviewExt.DoxUtil.CDoxSrcConfigXML._elemDictionary = null private
_file
string DoxPreviewExt.DoxUtil.CDoxSrcConfigXML._file = "" private
xml doxygen source specification file
The documentation for this class was generated from the following file:
C:/source/C#/VSIX-Doxygen-Extension/DoxPreviewExt/DoxUtil/DoxUtilDoxSrc.cs