VSIX Doxygen Preview Extension: ExtensionCommon.ExtensionContext Class Reference
ExtensionCommon.ExtensionContext Class Reference
Static Public Member Functions
static string GetDotExe ()
static string GetMscGenExe ()
static string GetPlantUmlJar ()
static string GetMimeTeXExe ()
Public Attributes
const string ConstExtensionName = @"DoxPreviewExt"
const string ConstExtensionImgResName = ExtensionContext.ConstExtensionName + @".DoxUtil.Resources."
const string ConstOptionsCategoryName = @"Doxygen Preview"
const string constDoxygenSourceBrowserURL = @""
const string doxCommadsHelpURL_ = @"https://www.stack.nl/~dimitri/doxygen/manual/commands.html"
const string graphvizHelpURL_ = @"http://www.graphviz.org/"
const string mscgenHelpURL_ = @"http://www.mcternan.me.uk/mscgen/"
const string planUMLHelpURL_ = @"http://plantuml.com/"
const string latexHelpURL_ = @"https://en.wikibooks.org/wiki/LaTeX/Mathematics"
const string ConstDoxygenExePath = @"C:/tools/doxygen/doxygen.exe"
const string ConstDoxOptionsActionSettingsName = @"Display and action settings"
const string ConstDoxOptionsConfigurationName = @"Doxygen configuration"
Properties
static string DoxygenPreviewTemplatePath [get, set]
Static Private Member Functions
static string SearchFile (string name)
Static Private Attributes
static List< string > _pathList
Member Function Documentation
GetDotExe()
static string ExtensionCommon.ExtensionContext.GetDotExe () inline static
References ExtensionCommon.ExtensionContext.SearchFile().
Referenced by DoxPreviewExt.Configuration.DoxConfigUserControl.DoxConfigUserControl_Load(), and DoxPreviewExt.DoxUtil.COptions.FindDotExe().
GetMimeTeXExe()
static string ExtensionCommon.ExtensionContext.GetMimeTeXExe () inline static
References ExtensionCommon.ExtensionContext.SearchFile().
Referenced by DoxPreviewExt.Configuration.DoxConfigUserControl.DoxConfigUserControl_Load(), and DoxPreviewExt.DoxUtil.COptions.FindMimeTeXExe().
GetMscGenExe()
static string ExtensionCommon.ExtensionContext.GetMscGenExe () inline static
References ExtensionCommon.ExtensionContext.SearchFile().
Referenced by DoxPreviewExt.Configuration.DoxConfigUserControl.DoxConfigUserControl_Load(), and DoxPreviewExt.DoxUtil.COptions.FindMscGenExe().
GetPlantUmlJar()
static string ExtensionCommon.ExtensionContext.GetPlantUmlJar () inline static
References ExtensionCommon.ExtensionContext.SearchFile().
Referenced by DoxPreviewExt.Configuration.DoxConfigUserControl.DoxConfigUserControl_Load(), and DoxPreviewExt.DoxUtil.COptions.FindPlantUmlJar().
SearchFile()
static string ExtensionCommon.ExtensionContext.SearchFile (string name) inline static private
Referenced by ExtensionCommon.ExtensionContext.GetDotExe(), ExtensionCommon.ExtensionContext.GetMimeTeXExe(), ExtensionCommon.ExtensionContext.GetMscGenExe(), and ExtensionCommon.ExtensionContext.GetPlantUmlJar().
Member Data Documentation
_pathList
List<string> ExtensionCommon.ExtensionContext._pathList static private
Initial value:
= new List<string>
                {
                        @"C:\Tools",
                        @"C:\Program Files",
                        @"C:\Program Files (x86)",
                }
ConstDoxOptionsActionSettingsName
const string ExtensionCommon.ExtensionContext.ConstDoxOptionsActionSettingsName = @"Display and action settings"
ConstDoxOptionsConfigurationName
const string ExtensionCommon.ExtensionContext.ConstDoxOptionsConfigurationName = @"Doxygen configuration"
ConstDoxygenExePath
const string ExtensionCommon.ExtensionContext.ConstDoxygenExePath = @"C:/tools/doxygen/doxygen.exe"
Referenced by DoxPreviewExt.Command.CommandDoxgenGeneratePreview.Perform().
constDoxygenSourceBrowserURL
const string ExtensionCommon.ExtensionContext.constDoxygenSourceBrowserURL = @""
Referenced by DoxPreviewExt.DoxUtil.CManager.UpdateConfigFile().
ConstExtensionImgResName
const string ExtensionCommon.ExtensionContext.ConstExtensionImgResName = ExtensionContext.ConstExtensionName + @".DoxUtil.Resources."
Referenced by DoxPreviewExt.DoxUtil.CPreviewImageBase.GetImage().
ConstExtensionName
const string ExtensionCommon.ExtensionContext.ConstExtensionName = @"DoxPreviewExt"
ConstOptionsCategoryName
const string ExtensionCommon.ExtensionContext.ConstOptionsCategoryName = @"Doxygen Preview"
doxCommadsHelpURL_
const string ExtensionCommon.ExtensionContext.doxCommadsHelpURL_ = @"https://www.stack.nl/~dimitri/doxygen/manual/commands.html"
graphvizHelpURL_
const string ExtensionCommon.ExtensionContext.graphvizHelpURL_ = @"http://www.graphviz.org/"
latexHelpURL_
const string ExtensionCommon.ExtensionContext.latexHelpURL_ = @"https://en.wikibooks.org/wiki/LaTeX/Mathematics"
mscgenHelpURL_
const string ExtensionCommon.ExtensionContext.mscgenHelpURL_ = @"http://www.mcternan.me.uk/mscgen/"
planUMLHelpURL_
const string ExtensionCommon.ExtensionContext.planUMLHelpURL_ = @"http://plantuml.com/"
Property Documentation
DoxygenPreviewTemplatePath
string ExtensionCommon.ExtensionContext.DoxygenPreviewTemplatePath static get set
Referenced by DoxPreviewExt.DoxUtil.CManager.UpdateConfigFile().
The documentation for this class was generated from the following file:
C:/source/C#/VSIX-Doxygen-Extension/DoxPreviewExt/App/DoxExtContext.cs